#!/usr/bin/env python

# Allow ^C to kill the process.
import signal
signal.signal(signal.SIGINT, signal.SIG_DFL)

try:
    from chemfp.commandline.ob2fps import main
    main()
except KeyboardInterrupt:
    raise SystemExit()
